create table if not exists test_statuses (
    name text primary key
);

insert into test_statuses(name)
    values ('PENDING'), ('QUEUED'), ('RUNNING'), ('DONE'), ('CANCELLED'), ('ERROR');

create table if not exists test_runs (
    run_id bigint primary key generated by default as identity,
    name text not null,
    status text references test_statuses(name) not null,
    result text
);
